version: '2'
services:
  db:
    container_name: db
    networks:
      - tomernet
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  web:
    image: alerta/alerta-web
    # volumes:
      # - $PWD/config/config.json:/web/config.json
    ports:
      - 8080:8080
    networks:
      - tomernet
    depends_on:
      - db
    links:
        - db:db
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance,slack,prometheus
    restart: always
networks:
    tomernet:
        driver: bridge
